services:
  postgre:
    image: "postgres:16.2-alpine3.19"
    env_file:
      - compose.env
    ports:
      - 54321:5432
  api:
    depends_on:
      - postgre
    build: ./backend
    env_file:
      - compose.env
    ports:
      - 3000:3000
    command:
      - "/usr/local/bin/ztmfapi"
