# this file is intended to run in github actions
services:
  postgres:
    image: "postgres:16.2-alpine3.19"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      postgres:
        condition: service_healthy
    image: ${API_IMAGE_URI}
    environment:
      - PORT
      - DB_ENDPOINT
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASS
      - AUTH_HS256_SECRET
      - AUTH_HEADER_FIELD
    ports:
      - ${PORT}:${PORT}
    command:
      - "/usr/local/bin/ztmfapi"
