name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
projects: ["CMS-Enterprise/44"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise summary of the bug
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, version, etc.
      placeholder: "e.g., Chrome 120 on macOS 14.2"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we verify this bug is fixed?
      value: |
        - [ ] Bug no longer occurs when following steps above
        - [ ] No regression in related functionality
        - [ ] Tests added/updated to prevent recurrence
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Significantly impacts usage
        - Critical - Blocks core functionality
    validations:
      required: false

  - type: input
    id: affected-component
    attributes:
      label: Affected Component
      description: Which part of the application is affected?
      placeholder: "e.g., ARS Control Viewer, Export functionality"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste links
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Any relevant console output, stack traces, or error messages
      render: shell
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found a temporary workaround?
      placeholder: Describe any workaround you've found...
    validations:
      required: false
