name: Feature Request
description: Request a new feature or enhancement
labels: ["feature"]
projects: ["CMS-Enterprise/44"]
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - General Feature
        - UI Component
        - Database Component
      default: 0
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Description
      description: Describe what happens when a user interacts with this feature
      placeholder: |
        When a user clicks X, they should see Y...
        The system should then Z...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what "done" looks like for this feature
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information, mockups, or references
      placeholder: Add any other context, screenshots, or links here
    validations:
      required: false
