version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/ui'
    schedule:
      interval: 'daily'
      time: '11:53'
      timezone: 'America/New_York'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    reviewers:
      - 'ATNoblis'
    versioning-strategy: increase