name: Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true

jobs:
  infrastructure:
    name: Deploy
    runs-on: ubuntu-latest
    # environment: tells github which configured environment to use
    environment: ${{ inputs.environment }}
    # env: tell this job which env vars to set
    env:
      ENV: ${{ inputs.environment }}
    # 👆 makes your eyes cross I know
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Get AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLEARN }}
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.10.3"
      
      # these last 2 steps use some bash magic to convert to lowercase: ${ENV VAR,,}
      - name: Terraform init and validate
        run: terraform -chdir=infrastructure init -backend-config="config/backend-${ENV,,}.tf"

      - name: Terraform apply
        run: terraform -chdir=infrastructure apply -no-color -var-file="tfvars/${ENV,,}.tfvars" -auto-approve
