name: Orchestration DEV

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  # diff:
  #   name: Check for Changes
  #   runs-on: ubuntu-latest
  #   outputs:
  #     backend: ${{ steps.backend.outputs.backend }}
  #     infrastructure: ${{ steps.infrastructure.outputs.infrastructure }}
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Check for changes in backend/
  #       id: backend
  #       run: echo "backend=$(git --no-pager diff --name-only origin/main backend/ | grep ".go\|.sum\|Dockerfile" | head -n 1)" >> $GITHUB_OUTPUT

  #     - name: Check for changes in infrastructure/
  #       id: infrastructure
  #       run: echo "infrastructure=$(git --no-pager diff --name-only origin/main infrastructure/ | grep ".tf\|.tfvars" | head -n 1)" >> $GITHUB_OUTPUT
        
  # backend:
  #   name: Backend
  #   needs: diff
  #   if: contains(needs.diff.outputs.backend, 'backend/')
  #   uses: ./.github/workflows/backend.yml
  #   with:
  #     environment: DEV
  #   secrets: inherit
      
  # # terraform apply should be run if there were changes to the backend that resulted in a new image
  # infrastructure:
  #   name: Infrastructure
  #   needs: 
  #     - diff
  #     - backend
  #   if: contains(needs.diff.outputs.infrastructure, 'infrastructure/') || !cancelled()
  #   uses: ./.github/workflows/infrastructure.yml
  #   with:
  #     environment: DEV
  #   secrets: inherit
  