name: Orchestration DEV

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    name: Test with list
    uses: ./.github/workflows/test.yml
    with:
      config: |
        run: concurrent
        tests:
          - path: http://localhost:8080/api/v1/users/current
          - expect:
              status: 400
              content-type: application/json
              body: unauthorized
