name: Orchestration DEV

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  diff:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.backend.outputs.backend }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in backend/
        id: backend
        run: echo "backend=$(git --no-pager diff --name-only origin/main backend/ | grep ".go\|.sum\|Dockerfile" | head -n 1)" >> $GITHUB_OUTPUT

  backend:
    name: Backend
    needs: 
      - analysis
      - diff
    if: contains(needs.diff.outputs.backend, 'backend/')
    uses: ./.github/workflows/backend.yml
    with:
      environment: DEV
    secrets: inherit
  
  ecrToken:
    name: Retrieve and Set ECR Token
    needs:
      - analysis
      - diff
    if: contains(needs.diff.outputs.backend, 'backend/')
    runs-on: ubuntu-latest
    steps:
      - name: Get AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLEARN }}
          role-duration-seconds: 900
          aws-region: us-east-1
      
      - id: getEcrToken
        run: |
          ecrToken=$(aws ecr get-login-password --region us-east-1)
          echo "::add-mask::$ecrToken"
          echo "ecrToken=$ecrToken" >> "$GITHUB_OUTPUT"
      
      - name: Update Secret
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'DEV_ECR_TOKEN'
          value: ${{ steps.getEcrToken.outputs.ecrToken }}
          repository: CMS-Enterprise/ztmf
          token: ${{ secrets.PAT }}

  functional:
    name: Functional Testing
    needs: 
      - analysis
      - diff
      - backend
      - ecrToken
    if: contains(needs.diff.outputs.backend, 'backend/')
    uses: ./.github/workflows/functional.yml
    with:
      imageUri: ${{ needs.backend.outputs.imageUri }}
    secrets:
      ecrToken: ${{ secrets.DEV_ECR_TOKEN }}
      
  infrastructure:
    name: Infrastructure
    needs: 
      - analysis
      - diff
      - backend
      - functional
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: DEV
    secrets: inherit
  