name: Orchestration DEV

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  analysis:
    name: Analysis
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  diff:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.backend.outputs.backend }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in backend/
        id: backend
        run: echo "backend=$(git --no-pager diff --name-only origin/main backend/ | grep ".go\|.sum\|Dockerfile" | head -n 1)" >> $GITHUB_OUTPUT
        
  backend:
    name: Backend
    needs: 
      - analysis
      - diff
    if: contains(needs.diff.outputs.backend, 'backend/')
    uses: ./.github/workflows/backend.yml
    with:
      environment: DEV
    secrets: inherit
       
  functional:
    name: Functional Testing
    needs: 
      - analysis
      - diff
      - backend
    if: contains(needs.diff.outputs.backend, 'backend/')
    uses: ./.github/workflows/functional.yml
    with:
      environment: DEV
      imageUri: ${{ needs.backend.outputs.imageUri }}
    secrets:
      ecrPass: ${{ needs.backend.outputs.ecrPass }}
      
  infrastructure:
    name: Infrastructure
    needs: 
      - analysis
      - diff
      - backend
      - functional
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: DEV
    secrets: inherit
  