name: Orchestration PROD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:   
  backend:
    if: ${{ github.event.pull_request.merged }}
    name: Backend
    uses: ./.github/workflows/backend.yml
    with:
      environment: PROD
    secrets: inherit
      
  # terraform apply should be run if there were changes to the backend that resulted in a new image
  infrastructure:
    name: Infrastructure
    needs: 
      - backend
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: PROD
    secrets: inherit
  