name: Orchestration PROD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:   
  analysis:
    name: Analysis
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/analysis.yml
    secrets: inherit

  backend:
    name: Backend
    if: ${{ github.event.pull_request.merged }}
    needs:
      - analysis
    uses: ./.github/workflows/backend.yml
    with:
      environment: PROD
    secrets: inherit
      
  infrastructure:
    name: Infrastructure
    if: ${{ github.event.pull_request.merged }}
    needs: 
      - analysis
      - backend
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: PROD
    secrets: inherit
  